---
# ec2 instance provisioning
#

# TODO Figure out jump hosts for private subnets
# TODO do not assign public ip by default and setup jump host forwarding
# TODO remove ssh group from non-bastion hosts

- hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    image: "{{ aws_ami_ssd }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_name }}"
    termination_protection: false
    monitoring: true
    count: 1
    wait: true
    public: true
  tags:
    - provision
  tasks:
    - name: launch instance(s)
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        group: "{{ group }}"
        assign_public_ip: "{{ public }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        region: "{{ region }}"
        monitoring: "{{ monitoring }}"
        termination_protection: "{{ termination_protection }}"
        wait: "{{ wait }}"
        instance_tags:
          Name: "{{ name }}"
          Environment: "{{ env_name }}"
        exact_count: "{{ count }}"
        count_tag:
          Name: "{{ name }}"
          Environment: "{{ env_name }}"
      register: ec2

    - name: wait for ssh
      wait_for: 
        state: started
        host: "{{ item.public_ip }}"
        port: 22 
        timeout: 300
      with_items: "{{ ec2.tagged_instances }}"
      when: "{{ wait }}"

    # - name: add to inventory
    #   add_host:
    #     name: "{{ item.public_ip }}"
    #     groups: "{{ group }}"
    #     with_items: "{{ ec2.tagged_instances }}"

- hosts: localhost
  tasks:
    - name: refresh
      meta: refresh_inventory

- hosts: "tag_Name_{{ name }}"
  become: true
  gather_facts: false
  tags:
    - provision
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
  roles:
    - { role: ubuntu }


# Destroy ec2 instance(s)
#

- hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    image: "{{ aws_ami_ssd }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_name }}"
    wait: true
  tags:
    - destroy
  tasks:
    - name: destroy instance(s)
      ec2:
        group: "{{ group }}"
        region: "{{ region }}"
        wait: "{{ wait }}"
        image: "{{ image }}"
        exact_count: 0
        count_tag:
          Name: "{{ name }}"
          Environment: "{{ env_name }}"  
