---
# Pull and install vimsical's om.next fork
#

- name: create directory
  become: true
  file:
    path: "{{ om_dir }}"
    state: directory

# Pull bug with untracked files
- name: reset repo
  become: true
  command: git reset --hard HEAD
  args:
    chdir: "{{ om_dir }}"

- name:  "pulling om branch: {{ om_branch }}"
  become: true
  git:
    repo: https://github.com/vimsical/om.git
    version: "{{ om_branch }}"
    dest: "{{ om_dir }}"
    update: true
    force: true
    accept_hostkey: true
  register: pull

- name: install
  become: true
  command: "{{ lein }} install"
  args:
    chdir: "{{ om_dir }}"
  when: pull.changed
