---
# Create an ec2 keypair
#

- name: create keypair
  ec2_key:
    name: "{{ aws_key_name }}"
    region: "{{ aws_region }}"
  register: ec2_key
  tags:
    - provision

- name: ssh folder
  file:
    path: ~/.ssh
    state: directory
  tags:
    - provision

- name: save private key
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "{{ aws_private_key }}"
    mode: 0600
  when: ec2_key.changed
  tags:
    - provision
