---
# Register API instances with the application load balancer

- hosts: localhost
  connection: local
  gather_facts: false
  tags: configure
  tasks:
    - include: alb_facts.yml
    - include: target_group_facts.yml

    - name: Register instance with alb http target
      command: >-
        aws elbv2 register-targets
        --target-group-arn {{ alb_http_target_group_arn }}
        --targets Id={{ hostvars[item].ec2_id }},Port={{ api_http_port }}
      with_items: "{{ groups['tag_Group_' + api_group_name] }}"

    # - name: Register instance with alb https target
    #   command: >-
    #     aws elbv2 register-targets
    #     --target-group-arn {{ alb_https_target_group_arn }}
    #     --targets Id={{ hostvars[item].ec2_id }},Port={{ api_http_port}}
    #   with_items: "{{ groups['tag_Group_' + api_group_name] }}"
    #   when: env_name == 'prod'
