---
# Register API instances with the application load balancer

- hosts: localhost
  connection: local
  gather_facts: false
  tags: configure
  tasks:
    - include: alb_facts.yml
    - include: target_group_facts.yml

    - name: Register instance with api target
      command: >-
        aws elbv2 register-targets
        --target-group-arn {{ alb_api_target_group_arn }}
        --targets Id={{ hostvars[item].ec2_id }},Port={{ api_http_port }}
      with_items: "{{ groups['tag_Group_' + api_group_name] }}"
