---
# Start ec2 instance(s)
#

# TODO do not assign public ip by default and setup jump host forwarding
# TODO remove ssh group from non-bastion hosts

- name: launch instance(s)
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    group: "{{ group }}"
    assign_public_ip: true # "{{ public }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    region: "{{ region }}"
    monitoring: "{{ monitoring }}"
    termination_protection: "{{ termination_protection }}"
    wait: "{{ wait }}"
    instance_tags:
      Name: "{{ name }}"
      Environment: "{{ env_name }}"
    exact_count: "{{ count }}"
    count_tag:
      Name: "{{ name }}"
      Environment: "{{ env_name }}"
  register: ec2
  tags: 
    - provision

# NOTE: it seems there ixs an issue with the registered output and the
# exact_count option causing the var not to be parsed, so we can't inspect its
# properties

# - debug: var="{{ (ec2.stdout|from_json) }}"

# - name: wait for ssh
#   wait_for: 
#     host: "{{ item.private_ip }}"
#     state: started
#     port: 22 
#     delay: 60
#     timeout: 300
#   with_items: "{{ (ec2.stdout|from_json).tagged_instances }}"
#   when: "{{ wait }}"
#   tags: 
#     - provision

# Destroy ec2 instance(s)
#

- name: destroy instance(s)
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    group: "{{ group }}"
    assign_public_ip: true # "{{ public }}"
    region: "{{ region }}"
    monitoring: "{{ monitoring }}"
    termination_protection: "{{ termination_protection }}"
    wait: "{{ wait }}"
    instance_tags:
      Name: "{{ name }}"
      Environment: "{{ env_name }}"
    exact_count: 0
    count_tag:
      Name: "{{ name }}"
      Environment: "{{ env_name }}"
  when: not termination_protection
  tags:
    - destroy
