---
# Destory dynamodb

- name: destroy s3 log bucket
  s3_bucket: name={{ ddb_s3_log_bucket }} state=absent

- name: destroy dynamo table
  dynamodb_table: name={{ ddb_table }} state=absent

- name: destroy IAM transactor role
  iam: iam_type=role name={{ datomic_transactor_role }} state=absent

- name: destroy IAM peer role
  iam: iam_type=role name={{ datomic_peer_role }} state=absent
