---
datomic_version: 0.9.5544
datomic_download_dir: "/tmp/datomic-{{ datomic_version }}"
datomic_home_parent: "/usr/local/bin"
datomic_home_name: "datomic-pro-{{ datomic_version }}"
datomic_home: "{{ datomic_home_parent }}/{{ datomic_home_name }}"
datomic_url: "https://my.datomic.com/repo/com/datomic/datomic-pro/{{ datomic_version }}/datomic-pro-{{ datomic_version }}.zip"
datomic_user: datomic
