---
# Datomic transactor provisioning
#

- hosts: localhost
  connection: local
  roles:
    - { role: dynamodb }

- include: ../ec2_instance/provision.yml
  vars:
    name: "{{ env_name }}_transactor"
    group: [ "{{ ssh_sg }}", "{{ transactor_sg }}" ]
    vpc_subnet_id: "{{ vpc.subnets[1].id }}"
    instance_type: m3.large
    count: 1
