---
# Configure OpsCenter agent for cassandra nodes
#

- name: get ec2 Facts
  action: ec2_facts

- name: Set opscenter node fact
  set_fact: opscenter_node={{ groups[[opscenter_group][0]][0] }}

- name:  Set opscenter ip fact
  set_fact: opscenter_ip="{{ hostvars[opscenter_node]['ansible_eth0']['ipv4']['address'] }}"

- name: Install Opscenter agent
  apt: pkg=datastax-agent state=present

- name: Configure Opscenter stomp
  shell: "echo stomp_interface: {{ opscenter_ip }} > /var/lib/datastax-agent/conf/address.yaml"

- name: Configure Opscenter agent SSL (disabled)
  shell: "echo use_ssl: 0 | tee -a /var/lib/datastax-agent/conf/address.yaml"

- name: Configure backup tmp directory
  shell: "echo tmp_dir: /data/cassandra/backup_tmp | tee -a /var/lib/datastax-agent/conf/address.yaml"

- name: Set address.yaml permissions
  file: path=/var/lib/datastax-agent/conf/address.yaml owner=cassandra group=cassandra mode=0664
  
- name: Create backup temp directory
  file: path=/data/cassandra/backup_tmp state=directory owner=cassandra group=cassandra mode=0755

- name: Opscenter agent startup
  service: name=datastax-agent state=restarted
