---
# Configure the Datastax community repos
#

# Repository
#
- name: add repository
  shell: >-
    echo "deb http://debian.datastax.com/community stable main" >
    /etc/apt/sources.list.d/cassandra.sources.list

- name: add repository key
  shell: >-
    curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
