---
# Pull the app repo and cut a jar
#

- name: create git_repo_dir
  file: path={{ git_repo_dir }} state=directory

- name: pull repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ git_repo_dir }}"
    update: true
    accept_hostkey: true
    force: true

- name: create uberjar
  shell: "{{ uberjar_command }}"
  environment: "{{ uberjar_environment }}"
  args:
    chdir: "{{ git_repo_dir }}"

- name: create jar_dir
  file: path={{ jar_dir }} state=directory owner={{ service_user }}

- name: move jar to jar_dir
  become: true
  copy:
    remote_src: true
    src: "{{ git_repo_dir }}/target/{{ jar_name }}"
    dest: "{{ jar_dir }}/{{ jar_name }}"
    owner: "{{ service_user }}"

- name: delete repo
  file: path={{ git_repo_dir }} state=absent

- name: create systemd unit folder
  become: true
  file: path=/etc/systemd/system state=directory

- name: copy systemd unit file
  become: true
  template:
    src: unit.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: reload systemd
  become: true
  command: systemctl daemon-reload

- name: start service
  become: true
  systemd:
    enabled: true
    name: "{{ service_name }}"
    state: started
