---
# Pull the app repo and cut a jar
#

- name: create git_repo_dir
  file: path={{ git_repo_dir }} state=directory

- name: "pulling {{ git_version }} from: {{ git_repo }}"
  git:
    repo: "{{ git_repo }}"
    version: "{{ git_version }}"
    dest: "{{ git_repo_dir }}"
    update: true
    force: true
    accept_hostkey: true

- name: clean
  command: "{{ lein }} clean"
  args:
    chdir: "{{ git_repo_dir }}"

- name: create uberjar
  become: true
  command: "{{ uberjar_command }} {{ uberjar_args }}"
  args:
    chdir: "{{ git_repo_dir }}"
    creates: "{{ git_repo_dir }}/target/{{ jar_name }}"
  environment: "{{ uberjar_environment }}"

- name: create jar_dir
  file: path={{ jar_dir }} state=directory owner={{ service_user }}

- name: move jar to jar_dir
  become: true
  copy:
    remote_src: true
    src: "{{ git_repo_dir }}/target/{{ jar_name }}"
    dest: "{{ jar_dir }}"
    owner: "{{ service_user }}"

- name: remove jar
  become: true
  file:
    path: "{{ git_repo_dir }}/target/{{ jar_name }}"
    state: absent

- name: create systemd unit folder
  become: true
  file: path=/etc/systemd/system state=directory

- name: copy systemd unit file
  become: true
  template:
    src: unit.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: start service
  become: true
  systemd:
    enabled: true
    daemon_reload: true
    name: "{{ service_name }}"
    state: restarted
