---
# Download and extract datomic pro
#

- name: install zip
  become: true
  apt: pkg=unzip

- name: create download dir
  file:
    path: "{{ datomic_download_dir }}"
    state: directory

- name: download archive
  become: true
  get_url:
    url_username: "{{ datomic_login }}"
    url_password: "{{ datomic_password }}"
    url: "{{ datomic_url }}"
    dest: "{{ datomic_download_dir }}/datomic.zip"
    force: yes

- name: unzip to datomic home dir
  become: true
  unarchive:
    remote_src: true
    src: "{{ datomic_download_dir }}/datomic.zip"
    dest: "{{ datomic_home_parent }}"
    creates: "{{ datomic_home_name }}"
    owner: "{{ datomic_user }}"
