---
# ALB sg
#

- name: create alb security group
  ec2_group:
    description: ALB security group
    name: "{{ alb_sg }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  tags: 
    - provision

# - name: destroy alb security group
#   ec2_group:
#     description: ALB security group
#     name: "{{ alb_sg }}"
#     region: "{{ aws_region }}"
#     state: absent
#     rules: []
#     rules_egress: []
#   tags:
#     - destroy
