---
# API sg
#

- name: create api security group
  ec2_group:
    description: API security group
    name: "{{ api_sg }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      # HTTP
      - proto: tcp
        from_port: 8080
        to_port: 8080
        group_name: "{{ alb_sg }}"
      # Websocket
      - proto: tcp
        from_port: 8081
        to_port: 8081
        group_name: "{{ alb_sg }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  tags: provision

# - name: destroy api security group
#   ec2_group:
#     description: API security group
#     name: "{{ api_sg }}"
#     state: absent
#   tags: destroy
