---
# Peer sg
#

- name: create peer security group
  ec2_group:
    description: Datomic peer security group
    name: "{{ peer_sg }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  tags: 
    - provision

- name: destroy peer security group
  ec2_group:
    description: Datomic peer security group
    name: "{{ peer_sg }}"
  tags:
    - destroy

# Transactor sg
#
- name: create transactor security group
  ec2_group:
    description: Datomic transactor security group
    name: "{{ transactor_sg }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 4334
        to_port: 4334
        group_name: "{{ peer_sg }}"
      - proto: tcp
        from_port: 4335
        to_port: 4335
        group_name: "{{ peer_sg }}"
      - proto: tcp
        from_port: 4336
        to_port: 4336
        group_name: "{{ peer_sg }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  tags: 
    - provision

- name: destroy transactor security group
  ec2_group:
    description: Datomic transactor security group
    name: "{{ transactor_sg }}"
  tags:
    - destroy

