---
# Redis sg
#

- name: create redis security group
  ec2_group:
    description: Redis security group
    name: "{{ redis_sg }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 6379
        to_port: 6379
        group_name: "{{ api_sg }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  tags: provision

# - name: destroy redis security group
#   ec2_group:
#     description: Redis security group
#     name: "{{ redis_sg }}"
#   tags: destroy
