---
# Configure cassandra cluster
#

# https://d0.awsstatic.com/whitepapers/AWS_Cassandra_Whitepaper.pdf
# https://www.datadoghq.com/blog/how-to-monitor-cassandra-performance-metrics/

- hosts: "tag_Group_{{ cassandra_group_name }}"
  become: true
  tags:
    - configure

  vars:
    cassandra_conf_dir: /etc/cassandra
    cassandra_data_dir: "{{ ebs_volume_mount_point }}/cassandra/data"
    cassandra_group: cassandra
    cassandra_user: cassandra
    datadog_checks:
      cassandra:
        instances:
          - host: localhost
            port: 7199
            cassandra_aliasing: true
        init_config:
          conf:
            - include:
                domain: org.apache.cassandra.metrics
                type: ClientRequest
                scope:
                  - Read
                  - Write
                name:
                  - Latency
                  - Timeouts
                  - Unavailables
                attribute:
                  - Count
                  - OneMinuteRate
            - include:
                domain: org.apache.cassandra.metrics
                type: ClientRequest
                scope:
                  - Read
                  - Write
                name:
                  - TotalLatency
            - include:
                domain: org.apache.cassandra.metrics
                type: Storage
                name:
                  - Load
                  - Exceptions
            - include:
                domain: org.apache.cassandra.metrics
                type: ColumnFamily
                bean_regex:
                  - .*keyspace=.*
                name:
                  - TotalDiskSpaceUsed
                  - BloomFilterDiskSpaceUsed
                  - BloomFilterFalsePositives
                  - BloomFilterFalseRatio
                  - CompressionRatio
                  - LiveDiskSpaceUsed
                  - LiveSSTableCount
                  - MaxRowSize
                  - MeanRowSize
                  - MemtableColumnsCount
                  - MemtableLiveDataSize
                  - MemtableSwitchCount
                  - MinRowSize
              exclude:
                keyspace:
                  - OpsCenter
                  - system
                  - system_auth
                  - system_distributed
                  - system_schema
                  - system_traces
            - include:
                domain: org.apache.cassandra.metrics
                type: Cache
                name:
                  - Capacity
                  - Size
                attribute:
                  - Value
            - include:
                domain: org.apache.cassandra.metrics
                type: Cache
                name:
                  - Hits
                  - Requests
                attribute:
                  - Count
            - include:
                domain: org.apache.cassandra.metrics
                type: ThreadPools
                path: request
                name:
                  - ActiveTasks
                  - CompletedTasks
                  - PendingTasks
                  - CurrentlyBlockedTasks
            - include:
                domain: org.apache.cassandra.db
                attribute:
                  - UpdateInterval
  pre_tasks:
    - name: create user
      become: true
      user:
        name: "{{ cassandra_user }}"
        state: present

  roles:
    - { role: cassandra }
    - { role: Datadog.datadog, become: yes, ansible_os_family: "Debian" }
