---
# Destroy environment
#

# Include the the provisioning playbooks, in reverse order

- include: transactor/provision.yml
- include: cassandra/provision.yml
- include: security_groups/provision.yml
- include: vpc/provision.yml
