---
# Provision AWS infrastructure
#

- include: ec2_keypair/provision.yml
- include: vpc/provision.yml
- include: cassandra/provision.yml
- include: transactor/provision.yml
- include: redis/provision.yml
- include: api/provision.yml
- include: alb/provision.yml
