---
# Provision AWS infrastructure
#

- name: provision infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: ec2_keypair }

- include: vpc/provision.yml
- include: security_groups/provision.yml
#- include: cassandra/provision.yml
- include: transactor/provision.yml

# - include: redis/provision.yml
# - include: alb/provision.yml
# - include: api/provision.yml
