---
# Configure api hosts
#

- hosts: "tag_Group_{{ api_group_name }}"
  tags:
    - configure

  vars:
    vimsical_user: vimsical

  pre_tasks:
    - name: create user
      become: true
      user:
        name: "{{ vimsical_user }}"
        state: present
