---
# API provisioning
#

- name: provision api instance(s)
  include: ../ec2_instance/provision.yml
  vars:
    name: "{{ api_group_name }}"
    group_name: "{{ api_group_name }}"
    security_groups:
      - "{{ ssh_sg_name }}"
      - "{{ api_sg_name }}"
      - "{{ peer_sg_name }}"
      - "{{ cassandra_sg_name}}"
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    instance_type: "{{ api_instance_type }}"
    count: "{{ api_instance_count }}"
