---
# API provisioning
#

- include: ec2_instance/provisioning.yml
  name: "{{ api_group_name }}"
  group_name: "{{ api_group_name }}"
  security_groups:
    - "{{ ssh_sg_name }}"
    - "{{ api_sg_name }}"
  instance_type: m3.large
  image: "{{ aws_ami_ssd }}"
  monitoring: true
  count: 2
