---
# API provisioning
#

- include: ec2_instance/provisioning.yml
  name: "{{env_name }}_api"
  groups: 
    - "{{ ssh_sg }}"
    - "{{ api_sg }}"
  instance_type: m3.large
  image: "{{ aws_ami_ssd }}"
  monitoring: true
  count: 2
