---
# Configure cassandra cluster
#

# https://d0.awsstatic.com/whitepapers/AWS_Cassandra_Whitepaper.pdf
# https://www.datadoghq.com/blog/how-to-monitor-cassandra-performance-metrics/

- hosts: "tag_Group_{{ cassandra_group_name }}"
  become: true
  tags:
    - configure

  vars:
    cassandra_conf_dir: /etc/cassandra
    cassandra_data_dir: "{{ ebs_volume_mount_point }}/cassandra/data"
    cassandra_group: cassandra
    cassandra_user: cassandra

  pre_tasks:
    - name: create user
      become: true
      user:
        name: "{{ cassandra_user }}"
        state: present

  roles:
    - { role: cassandra }
