---
# Configure Cassandra nodes
#

# Workaround
# https://github.com/ansible/ansible/issues/9260

- name: workaround
  hosts: all
  tasks: []
  tags: 
    - configure

- hosts: "tag_Name_{{ env_name }}_cassandra"
  become: true
  vars:
    cassandra_cluster_name: "vimsical_{{ env_name }}"
  roles:
    - { role: cassandra, tags: ["configure"] }
