---
# Configure cassandra cluster
#

# https://d0.awsstatic.com/whitepapers/AWS_Cassandra_Whitepaper.pdf
# https://www.datadoghq.com/blog/how-to-monitor-cassandra-performance-metrics/

- hosts: "tag_Group_{{ cassandra_group_name }}"
  become: true
  tags:
    - configure
  roles:
    - { role: cassandra }
