---
# Cassandra nodes
#

- include: ../ec2_instance/provision.yml
  vars:
    name: "{{ env_name }}_cassandra"
    group: [ "{{ ssh_sg }}", "{{ cassandra_sg }}" ]
    vpc_subnet_id: "{{ vpc.subnets[1].id }}"
    instance_type: m3.large
    count: 3
