---
# Cassandra nodes
#

- name: provision cassandra cluster
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ec2_instance
      name: "{{ env_name }}_cassandra"
      group: "{{ cassandra_sg }}"
      vpc_subnet_id: "{{ vpc.subnets[1].id }}"
      instance_type: m3.large
      count: 3

- name: install python2 on cassandra node
  hosts: "tag_Name_{{ env_name }}_cassandra"
  become: true
  gather_facts: false
  tasks:
    - name: python2
      raw: sudo apt-get install -y python-simplejson
  tags: 
    - provision

- name: set seed fact
  hosts: "tag_Name_{{ env_name }}_cassandra"
  gather_facts: false
  tasks:
    - name: set seed
      set_fact:
        seed: true
  tags: 
    - provision
    - configure

# OpsCenter
#

- name: provision opscenter
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ec2_instance
      name: "{{ env_name }}_opscenter"
      group: "{{ opscenter_sg }}"
      vpc_subnet_id: "{{ vpc.subnets[1].id }}"
      instance_type: t2.medium

- name: install python2 on opscenter node
  hosts: "tag_Name_{{ env_name }}_opscenter"
  become: true
  gather_facts: false
  tasks:
    - name: python2
      raw: sudo apt-get install -y python-simplejson
  tags: 
    - provision


