---
# Cassandra nodes
#

- name: provision cassandra instance(s)
  include: ../ec2_instance/provision.yml
  vars:
    name: "{{ cassandra_group_name }}"
    group_name: "{{ cassandra_group_name }}"
    security_groups: [ "{{ ssh_sg_name }}", "{{ cassandra_sg_name }}" ]
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    instance_type: "{{ cassandra_instance_type }}"
    count: "{{ cassandra_instance_count }}"
    ec2_volume_size: 80
    ec2_volume_path:

# - name: create keyspace
#   hosts: "{{ tag_Group_{{ cassandra_group_name }}[0] }}"
#   command: >-
#     cqlsh -e "create keyspace if not exists {{ cassandra_keyspace_name }} with replication = {'class': 'SimpleStrategy', 'replication_factor': {{ cassandra_replication_factor }} };"
