---
# Configure datomic transactor
#
- name: create data dir
  become: true
  file:
    path: "{{ datomic_data_dir }}"
    state: directory
    owner: "{{ datomic_user }}"

- name: create log dir
  become: true
  file:
    path: "{{ datomic_log_dir }}"
    state: directory
    owner: "{{ datomic_user }}"

- name: create config dir
  become: true
  file:
    path: "{{ datomic_config_dir }}"
    state: directory
    owner: "{{ datomic_user }}"

- name: copy config
  become: true
  template:
    src: "{{ datomic_transactor_properties_template }}"
    dest: "{{ datomic_config_dir }}/transactor.properties"
    owner: "{{ datomic_user }}"

- name: create systemd unit folder
  become: true
  file: path=/etc/systemd/system state=directory

- name: copy systemd unit file
  become: true
  template:
    src: datomic-transactor.service.j2
    dest: /etc/systemd/system/datomic-transactor.service

- name: reload systemd
  become: true
  command: systemctl daemon-reload

- name: start service
  become: true
  systemd:
    enabled: true
    name: datomic-transactor
    state: started
