---
# Install leiningen
#

- name: create lein dir
  become: true
  file: path={{ lein_dir }}

- name: download latest leiningen release
  become: true
  get_url:
    url: https://raw.github.com/technomancy/leiningen/stable/bin/lein
    dest: "{{ lein_dir }}"
    mode: 0755

- name: lein bootstrap
  command: lein version
